language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
addons:
  apt:
    sources:
    - cmake
    - sourceline: 'ppa:george-edison55/cmake-3.x'
    packages:
    - cmake
script: sh ./travis.sh
sudo: false