language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.7
   - g++-4.7
   - clang-3.5
before_install:
  - sudo apt-get remove cmake
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository -y ppa:george-edison55/precise-backports
  - sudo apt-get update
  - sudo apt-get install cmake
script: sh ./travis.sh
sudo: require