language: generic
os: osx
before_install:
  - curl -sSLo googletest-release-1.8.0.tar.gz https://github.com/google/googletest/archive/release-1.8.0.tar.gz
  - tar xzf googletest-release-1.8.0.tar.gz
  - cd googletest-release-1.8.0/googletest && cmake . && make && cd .. && cd ..
  - curl -sSLo https://superb-sea2.dl.sourceforge.net/project/asio/asio/1.10.8 (Stable)/asio-1.10.8.tar.gz
  - tar xzf asio-1.10.8.tar.gz
  - cd asio-1.10.8 &&  ./configure --without-boost && make && make install && cd ..
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
      before_install:
        - sudo apt-get remove cmake
        - sudo apt-get install software-properties-common
        - sudo add-apt-repository -y ppa:george-edison55/precise-backports
        - sudo apt-get update
        - sudo apt-get install cmake
        - curl -sSLo googletest-release-1.8.0.tar.gz https://github.com/google/googletest/archive/release-1.8.0.tar.gz
        - tar xzf googletest-release-1.8.0.tar.gz
        - cd googletest-release-1.8.0/googletest && cmake . && make && cd .. && cd ..
    - os: linux
      dist: trusty
      sudo: required
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - libc++-dev
            - libc++abi-dev
          sources: *sources
      before_install:
        - curl -sSLo googletest-release-1.8.0.tar.gz https://github.com/google/googletest/archive/release-1.8.0.tar.gz
        - tar xzf googletest-release-1.8.0.tar.gz
        - cd googletest-release-1.8.0/googletest && cmake -DCMAKE_CXX_FLAGS="-I/usr/include/c++/v1 -stdlib=libc++ -lc++abi" . && make && cd .. && cd ..
script: sh ./travis.sh
